name = "ControlToolbox"
uuid = "2ad4426d-adda-49cc-8f21-e6d1e16b49fa"
authors = ["Prateek Ganguli <prateek.ganguli@gmail.com>"]
version = "1.0.0"

[deps]
ControlSystemsBase = "aaaaaaaa-a6ca-5380-bf3e-84a91bcd477e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
ControlSystemsBase = "1.14.5"
LinearAlgebra = "1.11.0"
Plots = "1.40.14"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
